# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CSStickyHeaderFlowLayoutDemo' do
  use_frameworks!
  pod 'CSStickyHeaderFlowLayout', :path => '../'
end
